services:

  api:
    build: .

    container_name: docker_api_aula

    ports:
      - "3000:3000"

    env_file:
      - .env

    depends_on:
      - mongo

    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:latest

    container_name: mongo_db_aula

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest

    container_name: mongo_express_aula

    ports:
      - "8081:8081"

    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
      ME_CONFIG_OPTIONS_EDITORTHEME: dracula

    depends_on:
      - mongo

    restart: unless-stopped

volumes:
  mongo_data: